name: zampapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7 # <-- Pacchetto per l'upload di file

  # Utility packages
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2      # <-- Pacchetto per scegliere immagini

  # iOS style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  flutterfire_cli: ^0.2.7

flutter:
  uses-material-design: true

